In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [44]:
df = pd.read_csv('train.txt', sep = ';', names = ['text', 'emotion'])

In [45]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [46]:
emotions = df['emotion'].unique()
emotions_val = {}
i = 0
for emo in emotions :
    emotions_val[emo] = i
    i += 1

emotions_val

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [47]:
df['emotion'] = df['emotion'].map(emotions_val)

In [48]:
# 1. Making all text lowercase
df['text'] = df['text'].apply(lambda x : x.lower())

In [49]:
# 2. Removing punctuations

import string
def remove_punc(txt): 
    return txt.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punc)

In [50]:
# Removing numbers

def remove_nums(txt): 
    mod_txt = ""
    for i in txt: 
        if not i.isdigit():
            mod_txt += i
    return mod_txt

df['text'] = df['text'].apply(remove_nums)

In [51]:
# Removing emojis

def remove_nums(txt): 
    mod_txt = ""
    for i in txt: 
        if i.isascii():
            mod_txt += i
    return mod_txt

df['text'] = df['text'].apply(remove_nums)

In [52]:
#removing stopwords

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

def remove_stopwords(txt) :
    txt = txt.split(' ')
    cleaned_text = ""
    for word in txt:
         if not word in stop_words:
             cleaned_text += word+" "
    return cleaned_text

df['text'] = df['text'].apply(remove_stopwords)

In [53]:
df

,text,emotion
0,didnt feel humiliated,0
1,go feeling hopeless damned hopeful around some...,0
2,im grabbing minute post feel greedy wrong,1
3,ever feeling nostalgic fireplace know still pr...,2
4,feeling grouchy,1
...,...,...
15995,brief time beanbag said anna feel like beaten,0
15996,turning feel pathetic still waiting tables sub...,0
15997,feel strong good overall,5
15998,feel like rude comment im glad,1


In [56]:
# Koi fayda nhi

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df['text'])

print("Vocabulary : ", vectorizer.get_feature_names_out()) 
print("\nBoW matrix : \n", X.toarray()) 

Vocabulary :  ['aa' 'aaaaaaand' 'aaaaand' ... 'zum' 'zumba' 'zz']

BoW matrix : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size = 0.20, random_state = 42)

In [60]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [64]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)
predict_bow = nb_model.predict(X_test_bow)
print("Accuracy of BoW: ",accuracy_score(y_test, predict_bow))

Accuracy of BoW:  0.768125


In [65]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb_model.fit(X_train_tfidf, y_train)
predict_tfidf = nb_model.predict(X_test_tfidf)
print("Accuracy of TFIDF: ",accuracy_score(y_test, predict_tfidf))

Accuracy of TFIDF:  0.6609375


In [67]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()

In [ ]:
log_model.fit(X_train_bow,y_train)
predict_bow = log_model.predict(X_test_bow)
print("Accuracy of BoW: ",accuracy_score(y_test, predict_bow))

In [ ]:
log_model.fit(X_train_tfidf,y_train)
predict_tfidf = log_model.predict(X_test_tfidf)
print("Accuracy of BoW: ",accuracy_score(y_test, predict_tfidf))